### ISSUE TITLE
InvalidArgumentBucket POST must contain a field named 'key'. If it is specified, please check the order of the fields.keyB

### ISSUE THREAD

**Issue by MattCowski** [nukulb/s3-angular-file-upload#1]
Hey, this demo is super helpful since I've also been using the yo fullstack, but I keep running into this: 

`InvalidArgumentBucket POST must contain a field named 'key'. If it is specified, please check the order of the fields.keyB`

any clue how to fix?

**Comment by hemeda3** [comment]
My issue was that I have populated the S3 upload from using.  

`php
 $obj =json_decode($preSignedUrl['formInputs'], true);

    $filename = "ahmed.txt";
    foreach($obj as $key => $value)
{

    echo '<input type="text" value="'.$value.'" id="'.$key.'"></br>';
}

when I have changed :

`<input ........                    =>>>id="'.$key.'"  to  ===>>>>name="'.$key.'". .....>`

 it got resolved
 
 I thought may be this message `POST must contain a field named 'key'` means the S3 upload form must contains attribute name also
