### ISSUE TITLE
Curl POST/PUT?

### ISSUE THREAD

**Issue by kenetik** [nukulb/s3-angular-file-upload#14]
I love this, but would like to be able to use curl post/put functionality as well. Easy to implement? Thanks.

**Comment by nukulb** [comment]
@kenetik Thanks , I am glad you enjoyed this.

I am wondering what exactly are you looking to do with a curl post/put?

**Comment by kenetik** [comment]
@nukulb Thanks for the reply!

Essentially, this project only allows for file uploads via a web interface (form/browser input). Which works perfectly as expected. However, I would like to be able to use this same project to accept file uploads to my AWS S3 via a curl post. Example:

```$ curl -F file=@robomongo.log http://project.url/```

The goal would be for this to allow the upload file as the web interface does. However, the command results with the following error prompt:

```Cannot POST /```

I believe this is due to no PUT or POST route in express. 

Can you understand the goal?

**Comment by nukulb** [comment]
@kenetik I understand the goal but unfortunately this lies outside the scope of this project. If you start a new project or fork this I will be happy to help out.
